function createfigure(Y1, Y2, Y3, Y4)
%CREATEFIGURE(Y1, Y2, Y3, Y4)
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 20-Sep-2016 08:43:30

% Create figure
figure1 = figure('Name','Errors in Lat, Lon, Alt and Airspeed');

% Create subplot
subplot1 = subplot(4,1,1,'Parent',figure1,...
    'XTickLabel',{'0','1','2','3','4','5','6','7'},...
    'XGrid','on');
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(Y1,'Parent',subplot1);

% Create title
title('Errors in Lat, Lon, Alt and Airspeed');

% Create ylabel
ylabel('Lon (°)');

% Create subplot
subplot2 = subplot(4,1,2,'Parent',figure1,...
    'XTickLabel',{'0','1','2','3','4','5','6','7'},...
    'XGrid','on');
box(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(Y2,'Parent',subplot2);

% Create ylabel
ylabel('Lat (°)');

% Create subplot
subplot3 = subplot(4,1,3,'Parent',figure1,...
    'XTickLabel',{'0','1','2','3','4','5','6','7'},...
    'XGrid','on');
box(subplot3,'on');
hold(subplot3,'all');

% Create plot
plot(Y3,'Parent',subplot3);

% Create ylabel
ylabel('Alt (m)');

% Create subplot
subplot4 = subplot(4,1,4,'Parent',figure1,...
    'XTickLabel',{'0','1','2','3','4','5','6','7'},...
    'XGrid','on');
box(subplot4,'on');
hold(subplot4,'all');

% Create plot
plot(Y4,'Parent',subplot4);

% Create xlabel
xlabel('Time');

% Create ylabel
ylabel('Airspeed (m/s)');

