function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 19-Sep-2016 11:46:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
%% Uncomment the following line to preserve the Y-limits of the axes
     ylim(axes1,[49.3915 49.3975]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'DisplayName','Aircraft path');

% Create plot
plot(X2,Y2,'Parent',axes1,'Color',[1 0 0],'DisplayName','Path generated');

% Create title
title('Waypoint following');

% Create xlabel
xlabel('Longitud (°)');

% Create ylabel
ylabel('Latitude (°)');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.657822344204151 0.201080321935936 0.230283911671924 0.0915032679738562]);

