function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Sep-2016 11:51:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTickLabel',{'0','1','2','3','4','5','6','7','8'},...
    'XGrid','on');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 6500]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-10 160]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1);
set(plot1(2),'Color',[1 0 0]);

% Create xlabel
xlabel('Time (s)');

% Create ylabel
ylabel('Altitude (m)');

